version: '2.1'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pWp770521", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
    - "3306/tcp"
    volumes:
    - ./db:/var/lib/mysql
    - ./DbScripts:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_DATABASE=eftest
    - MYSQL_ROOT_PASSWORD=Wp770521
    networks:
    - mynetwork
  myapp:
    image: aspnetapp
    build:
       context: .
       dockerfile: Dockerfile
    ports:
    - 8080:80
    links:
    - mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
    - mynetwork
networks:
  mynetwork:
     driver: bridge
